---
# Deploy configuration files
- name: Remove basics example config files from rsyslog.d
  vars:
    __rsyslog_rules: "{{ __rsyslog_basics_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname }}"
    tasks_from: cleanup.yml
