---
# Deploy configuration files
- name: Install/Update basics input packages and generate configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: "{{ __rsyslog_basics_packages }}"
    __rsyslog_rules: "{{ __rsyslog_basics_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname }}"
    tasks_from: deploy.yml
