---
- name: Remove role config files from subdir
  file:
    path: >-
      {{ item.path | d(rsyslog_config_dir) }}/{{ item.filename | d((item.weight
      if item.weight | d() else rsyslog_weight_map[item.type | d("rules")]) +
      "-" + (item.name | d("rules")) + "." + (item.suffix | d("conf"))) }}
    state: absent
  with_flattened:
    - '{{ __rsyslog_rules }}'
  when:
    - item.filename | d() or item.name | d()
    - item.options | d() or item.sections | d()
  notify: restart rsyslogd
