---
# Deploy configuration files
- name: "Install/Update files input packages and generate
  configuration files in /etc/rsyslog.d"
  vars:
    __rsyslog_packages: "{{ __rsyslog_files_input_packages }}"
    __rsyslog_rules: "{{ __rsyslog_files_input_rules }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"

# yamllint disable rule:line-length
- name: "Create files input configuration file
  input-files-{{ _input.name }} in /etc/rsyslog.d"
  vars:
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-files-{{ _input.name }}"
        type: input
        state: "{{ _input.state | d('present') }}"
        sections:
          - options: |-
              input(type="imfile" file="{{ _input.input_log_path }}" tag="{{ _input.name }}")
              {{ lookup("template", "input_template.j2") }}
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"
  when:
    - _input.type | d() == 'files'
    - _input.input_log_path | d() | length > 0
# yamllint enable rule:line-length
