---
# Deploy configuration files
- name: Install/Update files input packages and generate configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: "{{ __rsyslog_files_input_packages }}"
    __rsyslog_rules: "{{ __rsyslog_files_input_rules }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"

- name: Create files input configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-files-{{ item.name }}"
        type: input
        state: "{{ item.state | d('present') }}"
        sections:
          - options: |-
              input(type="imfile" file="{{ item.input_log_path }}" tag="{{ item.name }}")
              {{ lookup('template', 'input_template.j2') }}
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"
  loop: '{{ logging_inputs }}'
  when:
    - item.type | d() == 'files'
    - item.input_log_path | d() | length > 0
