---
# Deploy configuration files
- name: Remove input files example config files from rsyslog.d
  vars:
    __rsyslog_rules: "{{ __rsyslog_files_input_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname ~ '/rsyslog' }}"
    tasks_from: cleanup.yml
