---
# Deploy configuration files
- name: Remove files input configuration files from /etc/rsyslog.d
  vars:
    __rsyslog_rules: "{{ __rsyslog_files_input_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname }}"
    tasks_from: cleanup.yml
