---
# Fluentd package name.
fluentd_package_name: fluentd

fluentd_ovirt_plugin_packages:
  - rubygem-fluent-plugin-rewrite-tag-filter
  - rubygem-fluent-plugin-secure-forward
  - rubygem-fluent-plugin-viaq_data_model
  - rubygem-fluent-plugin-elasticsearch

fluentd_log_level: info

fluentd_suppress_repeated_stacktrace: true

fluentd_emit_error_log_interval: 30
