---
- name: Set oVirt facts
  set_fact:
    rsyslog_role_rules: "{{ rsyslog_ovirt_rules }}"

- name: Remove oVirt configs
  include_role:
    name: "{{ role_path }}/roles/rsyslog"
    tasks_from: cleanup.yaml
