---
- name: Set ovirt_output_name
  set_fact:
    output_name: "{{ item.output_name }}"
  with_items: "{{ rsyslog_logs_collections }}"
  when: item.name == 'ovirt'

- name: Set oVirt facts
  set_fact:
    rsyslog_role_config_dir: "{{ rsyslog_ovirt_config_dir }}"
    rsyslog_role_rules: "{{ rsyslog_ovirt_rules }}"
    remove_role_config_dir: true

- name: Remove oVirt subdir
  include_role:
    name: logging/roles/rsyslog
    tasks_from: cleanup.yaml
