---
# Deploy configuration files
- name: Remove oVirt configs
  vars:
    __rsyslog_rules: "{{ __rsyslog_ovirt_rules }}"
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
