---
# Deploy configuration files
- name: Remove viaq configs
  vars:
    __rsyslog_rules: "{{ __rsyslog_viaq_rules }}"
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
