---
- name: Set Viaq facts
  set_fact:
    rsyslog_role_rules: "{{ rsyslog_viaq_rules }}"

- name: Remove viaq configs
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
