---
- block:

    - name: Install fluentd package
      yum:
        name: '{{ fluentd_package_name }}'
        state: latest
      when: manage_packages|default(true)
      notify: restart fluentd

    - name: Install oVirt fluentd plugins
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - '{{ fluentd_ovirt_plugin_packages }}'
      when:
        - manage_packages|default(true)
        - inventory_hostname in groups.engine
      notify: restart fluentd

    - name: Ensure fluentd configuration directory exists
      file:
        path: '{{ fluentd_config_dir }}'
        state: directory
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_dir_mode }}'

    - name: Ensure fluentd config.d directory exists
      file:
        path: '{{ fluentd_config_parts_dir }}'
        state: directory
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_dir_mode }}'

    - name: Create fluentd.conf
      template:
        src: fluentd.conf
        dest: '{{ fluentd_config_file }}'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

    - name: Install fluentd certificate
      copy:
        content: '{{ fluentd_ca_cert }}'
        dest: '{{ fluentd_ca_cert_path }}'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      when:
        - fluentd_use_ssl
        - fluentd_output_plugin|default("elasticsearch") == fluentd_output_plugin_fluentd
      notify: restart fluentd


- block:

    - name: Install fluentd elasticsearch CA certificate
      copy:
        content: '{{ fluentd_elasticsearch_ca_cert }}'
        dest: '{{ fluentd_elasticsearch_ca_cert_path }}'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

    - name: Install fluentd elasticsearch client certificate
      copy:
        content: '{{ fluentd_elasticsearch_client_cert }}'
        dest: '{{ fluentd_elasticsearch_client_cert_path }}'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

    - name: Install fluentd elasticsearch client key
      copy:
        content: '{{ fluentd_elasticsearch_client_key }}'
        dest: '{{ fluentd_elasticsearch_client_key_path }}'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

    - name: Configure fluentd system configurations
      template:
        src: fluentd-system-configurations.conf
        dest: '{{ fluentd_config_parts_dir }}/00-fluentd-system-configurations.conf'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

    - name: Configure oVirt processing
      template:
        src: ovirt-post-processing-common.conf
        dest: '{{ fluentd_config_parts_dir }}/25-ovirt-post-processing-common.conf'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: restart fluentd

  when:
    - fluentd_use_ssl
    - fluentd_output_plugin|default("elasticsearch") == fluentd_output_plugin_elasticsearch

# How to set fluentd_custom_config_files:
# fluentd_custom_config_files: [ '/path/to/custom0.conf', '/path/to/custom1.conf' ]
# The specified custom config files are copied to /etc/fluentd/config.d/ .
# If the array containse non-existing file, the deployment stops there with an error.
- name: Copy custom config files if they are specified in fluentd_custom_config_files variable array.
  copy:
    src: '{{ item }}'
    dest: '{{ fluentd_config_parts_dir }}'
    owner: '{{ item.owner | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode:  '{{ item.mode  | d("0400") }}'
  with_flattened:
    - '{{ fluentd_custom_config_files }}'
  notify: restart fluentd
