---
# SPDX-License-Identifier: GPL-3.0-only

# Imfile configuration setting
# ----------------------------
#
# List of rpm packages to install.
__rsyslog_files_input_packages: []

# __rsyslog_files_input_rules
#
# List of YAML dictionaries, each dictionary should contain ``rsyslogd``
# configuration in a special format. This list specifies ``rsyslogd``
# imfile configuration.
__rsyslog_files_input_rules:
  - '{{ __rsyslog_conf_imfile_modules }}'

# __rsyslog_conf_imfile_modules
#
# List of ``rsyslogd`` modules that enable logs from the local system to be
# received and parsed by the ``rsyslogd`` daemon.
__rsyslog_conf_imfile_modules:

  - name: 'input-files-modules'
    type: 'modules'
    sections:

      - comment: 'Reads log messages from file'
        options: |-
          module(load="imfile" mode="inotify")
