---
# Deploy configuration files
- name: Install/Update remote input packages and generate configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: "{{ __rsyslog_remote_packages }}"
    __rsyslog_rules:
      - name: "input-remote-modules"
        type: modules
        sections:
          - options: "{{ lookup('template', 'input_remote_module.j2') }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"

- name: Create basics input configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_input_name: "{{ item.name }}"
    __rsyslog_input_type: "{{ item.type }}"
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-remote-{{ item.name }}"
        type: input
        weight: "11"
        state: "{{ item.state | d('present') }}"
        sections:
          - options: "{{ lookup('template', 'input_remote.j2') }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"
  loop: '{{ logging_inputs }}'
  when: item.type | d() == 'remote'
