---
# Deploy configuration files
- name: Install/Update remote input packages and generate configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: "{{ __rsyslog_remote_packages }}"
    __rsyslog_rules:
      - name: "input-remote-modules"
        type: modules
        sections:
          - options: "{{ lookup('template', 'input_remote_module.j2') }}"
  include_tasks:
    file: deploy.yml

- name: Create basics input configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_input_name: "{{ remote_item.name }}"
    __rsyslog_input_type: "{{ remote_item.type }}"
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-remote-{{ remote_item.name }}"
        type: input
        weight: "11"
        sections:
          - options: "{{ lookup('template', 'input_remote.j2') }}"
  include_tasks:
    file: deploy.yml
  loop: '{{ logging_inputs }}'
  loop_control:
    loop_var: remote_item
  when: remote_item.type | d() == 'remote'
