---
fluentd_keepalive: 300

# Address of the elasticsearch server host.
fluentd_elasticsearch_host: ""

fluentd_elasticsearch_target_index_key: index_name

fluentd_elasticsearch_remove_keys: index_name

fluentd_elasticsearch_ssl_verify: false

# Address of the fluentd server host.
fluentd_fluentd_host: ""

# Directory of the output files when file output plugin is used

fluentd_file_output_dir: /var/log/fluentd

fluentd_logs_file_output: "{{ fluentd_file_output_dir }}/logging"

# Logs buffer configurations

fluentd_buffer_chunk_limit_logs: 4m

fluentd_flush_interval_logs: 10s

fluentd_buffer_queue_limit_logs: 8

fluentd_buffer_queue_full_action_logs: block

fluentd_retry_wait_logs: 60s

fluentd_retry_limit_logs: 17

fluentd_disable_retry_limit_logs: true

fluentd_max_retry_wait_logs: 3600

fluentd_flush_at_shutdown_logs: true

fluentd_num_threads_logs: 1

fluentd_slow_flush_log_threshold_logs: 20.0

fluentd_elasticsearch_type_name_logs: com.redhat.viaq.common

fluentd_elasticsearch_request_timeout_logs: 600
