---
# Deploy configuration files
- name: Install/Update oVirt input packages and generate configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: "{{ __rsyslog_ovirt_prereq_packages + __rsyslog_ovirt_packages }}"
    __rsyslog_rules: "{{ __rsyslog_ovirt_rules }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"

- name: Create oVirt input configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-ovirt-{{ item.name }}"
        type: input
        sections:
          - options: "{{ lookup('template', 'input_ovirt.j2') }}"
        state: "{{ item.state | d('present') }}"
  include_tasks:
    file: "{{ role_path }}/tasks/deploy.yml"
  loop: '{{ logging_inputs }}'
  when:
    - item.type | d('') == 'ovirt'
    - item.subtype | d('') in ['collectd','engine','vdsm']

- name: Allow rsyslog to listen on collectd port
  seport:
    ports: "{{ item.rsyslog_read_collectd_port | d(44514) }}"
    proto: tcp
    setype: syslogd_port_t
    state: present
  loop: '{{ logging_inputs }}'
  when:
    - item.type | d() == 'ovirt'
    - ansible_selinux.mode in ["enforcing", "permissive"]
  notify: restart rsyslogd
