---
# Deploy configuration files
- name: Remove viaq-k8s input configuration files from /etc/rsyslog.d
  vars:
    __rsyslog_rules: "{{ __rsyslog_viaq_k8s_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname }}"
    tasks_from: cleanup.yml
