---
# Deploy configuration files
- name: Remove Viaq-k8s role config files from subdir
  vars:
    __rsyslog_rules: "{{ __rsyslog_viaq_k8s_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname ~ '/rsyslog' }}"
    tasks_from: cleanup.yml
