---
# Elasticsearch configuration
# ---------------------

# Available configuration set
# ----------------------------

rsyslog_elasticsearch:
  - name: viaq-elasticsearch
    server_host: logging-es
    server_port: 9200
    index_prefix: project.


# Elasticsearch Rsyslog configuration rules
# ---------------------------

__rsyslog_elasticsearch_rules:

  - '{{ __rsyslog_conf_es_main_modules }}'
  - '{{ __rsyslog_conf_es_elasticsearch }}'

# Default elasticsearch configuration options [[[
# ---------------------------------

__rsyslog_conf_es_main_modules:

  - name: 'elasticsearch_main'
    type: 'modules'

    sections:

      - options: |-
          # Send to ElasticSearch
          module(load="omelasticsearch")

__rsyslog_conf_es_elasticsearch:

  - name: 'elasticsearch'
    type: 'output'
    path: '{{ rsyslog_config_dir }}'
    sections:

      - options: |-
          # omelasticsearch
          template(name="es_template" type="list") {
              property(name="$!all-json-plain")
          }
          template(name="es_template_nl" type="list") {
              property(name="$!all-json-plain")
              constant(value="\n")
          }

          # Add date to the end of the index name - index_prefix.yyyy-mm-dd,
          # based on the log timestamp.
          # This template sets "index_name"
          template(name="prefix_index_template" type="list") {
              property(name="$.index_prefix")
              property(name="$!@timestamp" dateFormat="rfc3339" position.from="1" position.to="4")
              constant(value=".")
              property(name="$!@timestamp" dateFormat="rfc3339" position.from="6" position.to="7")
              constant(value=".")
              property(name="$!@timestamp" dateFormat="rfc3339" position.from="9" position.to="10")
          }

          template(name="index_template" type="string" string="%$.index_name%")
          template(name="id_template" type="string" string="%$.es_msg_id%")

          ruleset(name="error_es") {
              action(name="es_bulk_errors" type="omfile" template="es_template_nl" file="{{ rsyslog_work_dir }}/es-bulk-errors.log")
          }

          ruleset(name="try_es") {
              if (strlen($.omes) > 0) and (strlen($.omes!status) > 0) then {
                  # retry case
                  if ($.omes!status == 200) or ($.omes!status == 201) or (($.omes!status == 409) and ($.omes!writeoperation == "create")) then {
                      stop # successful
                  }
                  if ($.omes!writeoperation == "unknown") or (strlen($.omes!error!type) == 0) or (strlen($.omes!error!reason) == 0) then {
                      call error_es
                      stop
                  }
                  if ($.omes!status == 400) or ($.omes!status < 200) then {
                      call error_es
                      stop
                  }
                  # else fall through to retry operation
              }
              if strlen($!es_msg_id) > 0 then {
                  set $.es_msg_id = $!es_msg_id;
              } else if (strlen($.omes) > 0) and (strlen($.omes!_id) > 0) then {
                  # retry
                  set $.es_msg_id = $.omes!_id;
              } else {
                  # NOTE: depends on rsyslog being compiled with --enable-uuid
                  set $.es_msg_id = $uuid;
              }
              if (strlen($.omes) > 0) and ( strlen($.omes!_index) > 0) then {
                  # retry
                  set $.index_name = $.omes!_index;
              } else {
                  set $.index_name = exec_template("prefix_index_template");
              }
          {% for res in rsyslog_elasticsearch %}
          {% if loop.length == 1 %}
              action(
                  type="omelasticsearch"
                  name="{{ res.name | default('viaq-elasticsearch') }}"
                  server="{{ res.server_host | default('logging-es') }}"
                  serverport="{{ res.server_port | default(9200) | int }}"
                  template="{{ res.template | default("es_template") }}"
                  searchIndex="{{ res.searchIndex | default("index_template") }}"
                  dynSearchIndex="{{ res.dynSearchIndex | default("on") }}"
                  searchType="{{ res.searchType | default("com.redhat.viaq.common") }}"
                  bulkmode="{{ res.bulkmode | default("on") }}"
                  writeoperation="{{ res.writeoperation | default("create") }}"
                  bulkid="{{ res.bulkid | default("id_template") }}"
                  dynbulkid="{{ res.dynbulkid | default("on") }}"
                  retryfailures="{{ res.retryfailures | default("on") }}"
                  allowUnsignedCerts="{{ res.allowUnsignedCerts | default("off") }}"
                  retryruleset="{{ res.retryruleset | default("try_es") }}"
                  usehttps="{{ res.usehttps | default("on") }}"
          {% if use_omelasticsearch_cert | default(true) %}
                  tls.cacert="{{ res.ca_cert | default("/etc/rsyslog.d/elasticsearch/es-ca.crt") }}"
                  tls.mycert="{{ res.cert | default("/etc/rsyslog.d/elasticsearch/es-cert.pem") }}"
                  tls.myprivkey="{{ res.key | default("/etc/rsyslog.d/elasticsearch/es-key.pem") }}"
          {% endif %}
              )
          {% else %}
          {% if loop.first %}
              if ( $.logs_collection == "{{ res.logs_collections_name }}" ) and ($.index_prefix startswith "{{ res.index_prefix }}") then {
                action(
                    type="omelasticsearch"
                    name="{{ res.name | default('viaq-elasticsearch') }}"
                    server="{{ res.server_host | default('logging-es') }}"
                    serverport="{{ res.server_port | default(9200) | int }}"
                    template="{{ res.template | default("es_template") }}"
                    searchIndex="{{ res.searchIndex | default("index_template") }}"
                    dynSearchIndex="{{ res.dynSearchIndex | default("on") }}"
                    searchType="{{ res.searchType | default("com.redhat.viaq.common") }}"
                    bulkmode="{{ res.bulkmode | default("on") }}"
                    writeoperation="{{ res.writeoperation | default("create") }}"
                    bulkid="{{ res.bulkid | default("id_template") }}"
                    dynbulkid="{{ res.dynbulkid | default("on") }}"
                    retryfailures="{{ res.retryfailures | default("on") }}"
                    allowUnsignedCerts="{{ res.allowUnsignedCerts | default("off") }}"
                    retryruleset="{{ res.retryruleset | default("try_es") }}"
                    usehttps="{{ res.usehttps | default("on") }}"
          {% if use_omelasticsearch_cert | default(true) %}
                    tls.cacert="{{ res.ca_cert | default("/etc/rsyslog.d/elasticsearch/es-ca.crt") }}"
                    tls.mycert="{{ res.cert | default("/etc/rsyslog.d/elasticsearch/es-cert.pem") }}"
                    tls.myprivkey="{{ res.key | default("/etc/rsyslog.d/elasticsearch/es-key.pem") }}"
          {% endif %}
                )
          {% elif loop.last %}
              else {
                action(
                    type="omelasticsearch"
                    name="{{ res.name | default('viaq-elasticsearch') }}"
                    server="{{ res.server_host | default('logging-es') }}"
                    serverport="{{ res.server_port | default(9200) | int }}"
                    template="{{ res.template | default("es_template") }}"
                    searchIndex="{{ res.searchIndex | default("index_template") }}"
                    dynSearchIndex="{{ res.dynSearchIndex | default("on") }}"
                    searchType="{{ res.searchType | default("com.redhat.viaq.common") }}"
                    bulkmode="{{ res.bulkmode | default("on") }}"
                    writeoperation="{{ res.writeoperation | default("create") }}"
                    bulkid="{{ res.bulkid | default("id_template") }}"
                    dynbulkid="{{ res.dynbulkid | default("on") }}"
                    retryfailures="{{ res.retryfailures | default("on") }}"
                    allowUnsignedCerts="{{ res.allowUnsignedCerts | default("off") }}"
          {% if res.retryfailures | default("on") == "on" %}
                    retryruleset="{{ res.retryruleset | default("try_es") }}"
          {% endif %}
                    usehttps="{{ res.usehttps | default("on") }}"
          {% if use_omelasticsearch_cert | default(true) %}
                    tls.cacert="{{ res.ca_cert | default("/etc/rsyslog.d/elasticsearch/es-ca.crt") }}"
                    tls.mycert="{{ res.cert | default("/etc/rsyslog.d/elasticsearch/es-cert.pem") }}"
                    tls.myprivkey="{{ res.key | default("/etc/rsyslog.d/elasticsearch/es-key.pem") }}"
          {% endif %}
                )
          {% else %}
              else if ( $.logs_collection == "{{ res.logs_collections_name }}" ) and ($.index_prefix startswith "{{ res.index_prefix }}") then {
                action(
                    type="omelasticsearch"
                    name="{{ res.name | default('viaq-elasticsearch') }}"
                    server="{{ res.server_host | default('logging-es') }}"
                    serverport="{{ res.server_port | default(9200) | int }}"
                    template="{{ res.template | default("es_template") }}"
                    searchIndex="{{ res.searchIndex | default("index_template") }}"
                    dynSearchIndex="{{ res.dynSearchIndex | default("on") }}"
                    searchType="{{ res.searchType | default("com.redhat.viaq.common") }}"
                    bulkmode="{{ res.bulkmode | default("on") }}"
                    writeoperation="{{ res.writeoperation | default("create") }}"
                    bulkid="{{ res.bulkid | default("id_template") }}"
                    dynbulkid="{{ res.dynbulkid | default("on") }}"
                    retryfailures="{{ res.retryfailures | default("on") }}"
                    allowUnsignedCerts="{{ res.allowUnsignedCerts | default("off") }}"
          {% if res.retryfailures | default("on") == "on" %}
                    retryruleset="{{ res.retryruleset | default("try_es") }}"
          {% endif %}
                    usehttps="{{ res.usehttps | default("on") }}"
          {% if use_omelasticsearch_cert | default(true) %}
                    tls.cacert="{{ res.ca_cert | default("/etc/rsyslog.d/elasticsearch/es-ca.crt") }}"
                    tls.mycert="{{ res.cert | default("/etc/rsyslog.d/elasticsearch/es-cert.pem") }}"
                    tls.myprivkey="{{ res.key | default("/etc/rsyslog.d/elasticsearch/es-key.pem") }}"
          {% endif %}
                )
          {% endif %}
              }
          {% endif %}
          {% endfor %}
          }

          call try_es
