# Viaq rpm packages

# __rsyslog_viaq_prereq_packages
#
# List of prerequired rpm packages for viaq
__rsyslog_viaq_prereq_packages: ['nmap-ncat', 'systemd-python', 'policycoreutils', 'checkpolicy', 'policycoreutils-python']

# __rsyslog_viaq_packages
#
# List of rpm packages for viaq
__rsyslog_viaq_packages: ['rsyslog-mmnormalize']
